### ISSUE TITLE
Add an `--open` option

### ISSUE THREAD

**Issue by Nugine** [thecoshman/http#106]
Like `cargo doc --open`, `http --open` will be helpful.

**Comment by nabijaczleweli** [comment]
This is partially a duplicate of #10, which ended with, quoth the pirate:
> Changed my mind on this one, copying into the clipboard automatically is messy for the user. Having a cli arg to say you want to do this is stupid.
>
> Working out *what* to copy is also very tedious.

And partially another platform-specific nightmare (`ShellExecute()` on Win32, `www-browser`/`x-www-browser`/`$BROWSER` on debians, with other distros likely having other tendencies, something good:tm: on Darwin, *no* idea about conventions of the various Berkeley derivatives).

Closing due to the two points outlined above.
