### ISSUE TITLE
Handle POST

### ISSUE THREAD

**Issue by nabijaczleweli** [thecoshman/http#12]
HTTP defines POST in [RFC7231](https://tools.ietf.org/html/rfc7231). Support therefor would go a long way towards full write support.

**Comment by nabijaczleweli** [comment]
> [The POST method requests that the target resource process the
   representation enclosed in the request according to the resource's
   own specific semantics.](https://tools.ietf.org/html/rfc7231#section-4.3.3)

Since we don't have any "specific semantics" we should NOT handle this.

**Comment by thecoshman** [comment]
I believe that point four covers what we want well enough:

> Creating a new resource that has yet to be identified by the origin server; and

We could either upload them to a `<root>/uploads` directory or (preferably) upload the files to the folder specified in the URL

**Comment by nabijaczleweli** [comment]
But that's exactly what PUT does and that's implemented.

**Comment by thecoshman** [comment]
I'm not sure what the headers for a POST request would look like. With PUT, you provide a the exact path (relative to server root obviously) for where this file should be hosted, and that can override what is already there. With POST, you would not provide a file name, just a folder. We can there for name the files as we see fit, probably just "upload_N".

Consider the idempotence, PUT you can repeat over and over and only see no difference from doing once to many times. With POST, each time you perform the exact same request, a new resource could be created, or our server could decide that when you POST some data, it is given a name based on it's hash, and just stored in a folder in the root.

Your problem seems to be that there is no predefined behaviour, yet you miss the fact that you are free to do what you see fit. Of course, simply rejecting saying that method isn't allowed is also 'ok', but IMO, not ok :P

**Comment by nabijaczleweli** [comment]
The POST request is *in every way* identical to the PUT request, except that it might be handled differently due to specific semantics regarding the *targeted resource*. We have no such resources.
