### ISSUE TITLE
Confusing `PREFIX` environment variable for installer

### ISSUE THREAD

**Issue by alejandro-colomar** [thecoshman/http#156]
https://github.com/thecoshman/http/blob/7e3962839a07cc035f6a387eb3281c163021c30f/README.md?plain=1#L59

Huh!  I find that variable quite confusing.  `prefix` is usually `/usr/local` (or `/usr`), `exec_prefix` is usually `$prefix`, and `bindir` is usually `$exec_prefix/bin`.  Where did this `PREFIX` as a `bindir` come from?

<https://www.gnu.org/prep/standards/html_node/Directory-Variables.html>

**Comment by nabijaczleweli** [comment]
It's not that deep: I wrote it once at the grand old age of 16 and never looked at it again – ![](https://github.com/thecoshman/http/assets/6709544/d9a47b4c-ed44-4022-9776-b53149c4c6e0)

If I wrote it today I'd do `-o "${PREFIX-/usr/local}/bin/http$exe_suffix"` or whatever, yeah. And write it so it's less of an eye-sore. Frankly, I'd just refuse to write it instead of writing it to tick a box, but, well. the mistakes of youth.

There have probably been a grand total of 0 users overall and it hasn't worked since at least the travis implosion (years at this point), so any expectation/usability/compatibility concern is moot anyway.
