### ISSUE TITLE
Non pretty html

### ISSUE THREAD

**Issue by thecoshman** [thecoshman/http#17]
Petty issue really, but [this](https://github.com/thecoshman/http/blob/master/assets/directory_listing.html#L19) should be wrapped in a <p> tag (personal preference more than anything). I would change it, but don't know if that's going to break the way the templates work, I doubt it would, but just encase.

**Comment by thecoshman** [comment]
[this too](https://github.com/thecoshman/http/blob/master/assets/error.html#L14)

**Comment by nabijaczleweli** [comment]
Re [directory_listing.html#L19](https://github.com/thecoshman/http/blob/master/assets/directory_listing.html#L19): it's in a `<div>`, can't use `<p>` because we have a linked list.

Re [error.html#L14](https://github.com/thecoshman/http/blob/master/assets/error.html#L14): this is [sometimes empty](https://github.com/thecoshman/http/blob/master/src/ops.rs#L91) but we wrap it with `<p>` [in](https://github.com/thecoshman/http/blob/master/src/ops.rs#L67) [code](https://github.com/thecoshman/http/blob/master/src/ops.rs#L157).

**Comment by thecoshman** [comment]
I don't follow you'r logic for the first... why can't you have `<div><p>...</p><ul>...</ul></div>`?

**Comment by nabijaczleweli** [comment]
Because that will create distance between the opening line and the list, and that's ugly.

**Comment by thecoshman** [comment]
Then you are being bad by using the html for layout. CSS is where layout should be performed. I also see other issues with the html. Also, correct me If I'm wrong... but is this html baked into the binary? Just curious.

**Comment by nabijaczleweli** [comment]
If you could actually *read* you'd know that I do use CSS for layout, but very well, I can make this completely abhorrent by applying CSS where it's not needed. What "other issues"?
Yes it is.

**Comment by nabijaczleweli** [comment]
Do you have any concrete complaints? If so, we can put them in #28. If no, we can close this in #28.
