### ISSUE TITLE
Larger, highlighted, click target for opening folders/files

### ISSUE THREAD

**Issue by thecoshman** [thecoshman/http#50]
Rather than just the text, for the file/folder name itself, the link should be of a larger html element so that there is more to click. It should also have a hover effect that highlights what you are over so it's clear

**Comment by nabijaczleweli** [comment]
I don't like this...

**Comment by NawfelBgh** [comment]
Do you have some particular reasons for not wanting this? @nabijaczleweli

**Comment by nabijaczleweli** [comment]
Clutter, 300 layers of magic, probably a shitton of workarounds for every occasion, and this is not something an average (i.e. stupid) end-user will see/use extensively.
I absolutely abhor bloated user interfaces and this is the first step to one.

**Comment by NawfelBgh** [comment]
> Clutter, 300 layers of magic, probably a shitton of workarounds for every occasion

I think you are very biased against this feature. It isn't that hard to implement. I don't see what workarounds and magic you are talking about.

> not something an average (i.e. stupid) end-user will see/use extensively.

I use this server from my mobile phone since it's, thanks to you, the only lightweight one that I know of which supports correct video streaming. It's just a shame that the interface isn't tailored for mobile devices.

In mobile, I keep hitting the wrong links all the time. I also need to zoom to be able to click and to scroll left and right to read the file names. That's just counter tedious. I also used this server from a smart TV and had a similar bad experience.

Why limit the potential users of this useful software?

> I absolutely abhor bloated user interfaces and this is the first step to one.

Making bigger click targets with hover isn't bloated user interface in my opinion.

**Comment by nabijaczleweli** [comment]
> hard to implement

What I see is "bigger links" but what I think pirate thinks is that GDrive SS.

> workarounds and magic 

Baby, this is wubdev.

> tailored for mobile devices

That's #51 tho

> with hover 

There's no hover on mobile

---

I'm all for an improved iface (like big links) for mobile, but I'm strongly against bloating the interface (where bloating - reducing information density) for non-mobile, which would be achieved by making a GDrive-like iface; I can settle for bigger icons (I think I can steal ~2x bigger ones from the same source) on dtop.

**Comment by NawfelBgh** [comment]
>> tailored for mobile devices
>
>That's #51 tho

I see your point now. You are against having "Larger, highlighted, click targets" for the desktop version.

>There's no hover on mobile

That's true. I was assuming that the intent of this issue was to have a consistent look across mobile and desktop. In that case, the hover is a necessary for desktop users so that they see what they don't click links unintentionally.

> I'm all for an improved iface (like big links) for mobile, but I'm strongly against bloating the interface (where bloating - reducing information density for no real gain) for non-mobile

Thanks for making your point clear. I'm also against wasting space in desktop.

**Comment by nabijaczleweli** [comment]
A consistent look is stupid to have, as both platforms require very different approaches, IMO.

**Comment by NawfelBgh** [comment]
What is more beautiful to your eye?

This:

![screenshot from 2017-01-28 01-06-34](https://cloud.githubusercontent.com/assets/1393737/22392210/2d8e2eba-e4f7-11e6-93ac-f08c35934147.png)

Or this:

![screenshot from 2017-01-28 01-16-03](https://cloud.githubusercontent.com/assets/1393737/22392237/6312d52c-e4f7-11e6-8211-17032d3e1cff.png)

I prefer the first one and I think that one can reasonably be used by both desktop and mobile with minimal change. What do you think?

**Comment by NawfelBgh** [comment]
For record, this is how github looks like in mobile:

![screenshot from 2017-01-28 01-25-23](https://cloud.githubusercontent.com/assets/1393737/22392396/d4393b5a-e4f8-11e6-8707-56220aa9b19c.png)

**Comment by nabijaczleweli** [comment]
> one and I think that one can reasonably 

They're identical, but it's more of a desktop feel (requires precision).

> record, this 

That's much more of a mobile feel, once cell per file, link all over it.

---

Have we reached a point where we agree that *this particular* solution (GDrive-like) is bad in the general case? If so, we can move on to #51, that is, a different look for mobile (I like the GH solution I might just steal it).

**Comment by NawfelBgh** [comment]
>Have we reached a point where we agree that this particular solution (GDrive-like) is bad in the general case?

* I agree that we shouldn't waste space like google drive.
* I think that having github-like look in desktop is nice. Do you agree?

**Comment by nabijaczleweli** [comment]
Well we have exactly that, so yes.

Closing due to discussion.

**Comment by thecoshman** [comment]
You have failed to understand the intention of this ticket.

There are two aspects to it. One is that the link for files/folder should not simply be the name of the file itself. This is easily done by wrapping the `<a>` tag around a different element. Two, add row highlights as you move your mouse over the listings. This again is not that hard to do.

I think the current html that is used to populate the directory listing might need to be redone, but that is not a big problem as we do not have much that relies on it being the way it currently is. And yes, we can all agree that making the UI very stretched out with lots of white space is not a good thing, but that is not what this ticket is attempting to get.

The core of this ticket is to increase the target area, which is one of the most basic concepts of UX. It does not require that the page become full of white space.

**Comment by nabijaczleweli** [comment]
> should not simply be 

(a) It's not, (b) what should it be?

> row highlights 

ez$

> be redone, but 

In what fashion?

> relies on it 

Only `HttpHandler::handle_get_dir_listing()` internals, yes

> making the UI
> not what this
> does not require 

Thank god

> the target area, which 

Can do

**Comment by nabijaczleweli** [comment]
Check out the `improvement/50-rework-dir-listing` branch for improvements, but rundown so far is that we have row highlighting and the whole row is clickable.

![SS](https://cloud.githubusercontent.com/assets/6709544/22400937/9615fadc-e5c2-11e6-862d-a92418d54a78.png)

**Comment by thecoshman** [comment]
Ah yeah, not the nicest impl, but good enough for now. I think that we would have to use a div based layout... but might be able to tweak the css to remove the borders between cells... don't worry too much though.

**Comment by nabijaczleweli** [comment]
I'm going to take that as "we can do small improvements later" but v0v for now

**Comment by NawfelBgh** [comment]
I propose these changes:

* Change the color scheme to look good with white background (btw @nabijaczleweli, why is the background gray in your screenshots?)
* Remove underline from titles;
* Remove table borders;
* Add a `border-bottom` like in the mobile version;
* Also: directory rows should have an empty `<a href="..."></a>` so that users can click the size area.

![screenshot from 2017-01-31 23-48-55](https://cloud.githubusercontent.com/assets/1393737/22488176/eb716fa2-e810-11e6-90fa-e8a7231b706a.png)


### Proposed changes to the CSS

```diff
diff --git a/assets/directory_listing.html b/assets/directory_listing.html
index 66bed12..d596d57 100644
--- a/assets/directory_listing.html
+++ b/assets/directory_listing.html
@@ -34,11 +34,21 @@
 
       td > a {
         display: block;
+        text-decoration: none;
       }
 
       tr:hover {
-        background-color: #7f7f7f80;
+        background-color: #eee;
+      }
+
+      tr {
+        border-bottom: solid 1px #ccc;
       }
+      
+      table {
+        border-collapse: collapse;
+      }    
+            
     </style>
   </head>
   <body>
```

**Comment by nabijaczleweli** [comment]
> the background gray 

Probably because I set my browser-wide default to grey so I still have some corneas left by the time I'm 18 :P

As for the rest of the changes: sure, I'll experiment some.

**Comment by nabijaczleweli** [comment]
Did all suggested changes, see referenced commit

**Comment by NawfelBgh** [comment]
Thanks, 4fe9b62a89251bcce0756 addresses all the issues raised in my last comment.
