### ISSUE TITLE
Option to not leave the subdirs of the hosted directory

### ISSUE THREAD

**Issue by nabijaczleweli** [thecoshman/http#71]
Submitting for extended discussion.

> [22:57] Pirate: @((бан *)наб)() Would it be worth adding a way to control what symlinks are followed? like, if you http to host /foo then you can follow symlinks within /foo but if a symlink goes to /bar the target isn't sent to you. A sort of sandboxing for symlinks
> [22:57] ((бан *)наб)(): That would need a very explicit config
> [22:58] Pirate: Would it?
> [22:58] ((бан *)наб)(): Do you have a use-case?
> [22:59] Pirate: I mean, if you host with in /foo/bar, and turn on this option, you know that the symlinks within that folder can only point to files/folders within /foo/bar
> [23:00] ((бан *)наб)(): oh, then just don't enable symlinks at all
> [23:01] ((бан *)наб)(): also, how would you treat a /foo/henlo -> /bar/benlo -> /foo/bai.txt?
> [23:06] Pirate: so, you want to host /foo/bar, symlinks within /goo/bar are fine to follow. But symlinks to outside of /foo/bar are a no no, except those to /bar
> [23:07] Pirate: I mean, I think the sandboxing would be a fairly good thing to add
> [23:07] Pirate: weather or not being to add additional paths that can be targets :blobshrug:

**Comment by thecoshman** [comment]
Yeah, I think I failed to explain properly what I was thinking off there. I guess to start with, I need to ask a few questions about the currently handling of symlinks.

Let's try this scenario; we run http from a folder `/foo` and that contains a symlink `/foo/file` which targets `/bar/file`, and we have not disabled symlinks. I believe currently that if you attempted to `GET file`, that will be a request to server `/foo/file` which http will detect as a symlink and follow to give you the contents of `/bar/file`, correct (question one)? If we had disabled symlinks, what will be served up by that request (question two)?

Now, you should be able to see that whilst when I ran http in the above scenario it was only 'exposing' `/foo` it turns out that I am also exposing files that are outside of that directory. This is why I was initially hesitant to have symlinks enabled by default.

Now, I am thinking that _maybe_ we could could add a toggle that will 'sandbox' the symlinks, such that the above request `GET file` will be handled as if symlinks were disabled (because the target /bar/file` is not within the directory being hosted). If however we have the symlink `/foo/file_two` that linked to `/foo/longPath/file` it would be followed. 

This would be an initial feature request, to limit the targets of symlinks that can be served to only targets files within the same folder as http is running from. 

Assuming we go with that feature, then I would see a next step would be the ability to add additional paths that can served as the target of symlinks.

**Comment by nabijaczleweli** [comment]
Question one: yes.
Question two: a secure 404:
![Q2](https://user-images.githubusercontent.com/6709544/41306781-7f985306-6e77-11e8-8b1b-2b9beeb23579.png)

Yep, that is a security concern.

Again: yes, good idea; and "symlink sandboxing" is a great name.
