### ISSUE TITLE
Consider changing the project's name

### ISSUE THREAD

**Issue by bbigras** [thecoshman/http#83]
"http" isn't the best name. If search "http" on any Linux distro I get thousands of results and the name collides with the very popular [httpie](https://github.com/jakubroztocil/httpie).

Why not call it `httplz`?

**Comment by nabijaczleweli** [comment]
Changing "the project"'s name is gonna be tricky, as (a) the repo is, sure renameable, but (b) the `crates.io` entry (which is actually `https` because \~squatters\~) is not (and (c) the name is actually technically Host These Things Please, but I'm being pedantic here).
However, we do provide both `http` and `httplz` executables by default.

As for "searching »http« on [a] Linux distro" – I don't know how to do that/what you mean by it, so I don't know how to help in that regard.

Also consider: #35

**Comment by bbigras** [comment]
> Changing "the project"'s name is gonna be tricky, as (a) the repo is, sure renameable, but (b) the crates.io entry (which is actually https because ~squatters~) is not (and (c) the name is actually technically Host These Things Please, but I'm being pedantic here).

Gotcha.

> As for "searching »http« on [a] Linux distro" – I don't know how to do that/what you mean by it, so I don't know how to help in that regard.

Sorry I wasn't clear. I mean that I want to include "Host These Things Please" in distro I'm using right now, if it's not already included. If I search for "http", I'll have a hard time trying to find it.

I think the solution is to search for your username, since packages are built from github sources.

I'm guessing it's fine if I call the package "httplz".

**Comment by nabijaczleweli** [comment]
I think that's the best idea, yeah (unless Pirate wants to come up with an altname, which I doubt).

**Comment by bbigras** [comment]
Good. I added httplz to NixOS https://github.com/NixOS/nixpkgs/pull/60304

**Comment by nabijaczleweli** [comment]
Delightful!

**Comment by thecoshman** [comment]
I am ok with these names 😃
