### ISSUE TITLE
Config files!

### ISSUE THREAD

**Issue by thecoshman** [thecoshman/http#99]
I want to be able to have all the cli options (other than this one itself, let's not go recursive) configurable via a config file that I can just save.

The config file will have to say what what paths are being shared, there is no implied current directory.

I think most of the current CLI options should be disabled if using a config file, I can't really think of any for which it makes sense.

One option that _maybe_ could also be used is being able to set if the config file should be watch such that on saving changes to it, the running instance of http will automatically pick them up, or maybe a way to tell http to reload the config; kinda like you can with nginx.

Maybe a 'validation' mode, that just parses the config file and reports any errors.

I think that `-c` and `--configfile` could be used for this. I don't think we need to support multiple config files being used in parallel

Format wise... I'm not too sure... we could get very hipster an support multiple formats. XML is kinda nice as we could have a spec thing to go along with it. Json is... well... Json... maybe some sort of custom plain text format thing? Maybe we start by trying some formats and see which look nicest?

**Comment by nabijaczleweli** [comment]
Use `http $(cat myconf)` if you like, which has the added benefit of not having to rewrite option parsing.

Live reload is an incredible pain in the ass, especially since http is essentially stateless (save for a few cheap transient things we store in `$TMP`).

Plus, actually changing the config on the fly requires implementing process restart in-application (or just `exec()`ing, which, well, what's the point).

For reference, one of my systemd services; note that it'd be trivial to use the standard systemd tooling (`EnvironmentFile=` or w/e it was) to load the config from somewhere on disk:
```ini
$ nabijaczleweli@tarta:~$ systemctl cat http-fo*
# /etc/systemd/system/http-foreign.nabijaczleweli.xyz.service
[Unit]
Description=http for foreign.nabijaczleweli.xyz at :8205
Wants=network-online.target
After=network-online.target

[Service]
ExecStart=/home/nabijaczleweli/.cargo/bin/http -p 8205 -e /var/www/foreign.nabijaczleweli.xyz/html --gen-path-auth priv --proxy X-Forwarded-For:127.0.0.1
KillSignal=SIGINT

[Install]
WantedBy=multi-user.target
```
